### ISSUE TITLE
Ship.yaml inline asset file modes are not set correctly

### ISSUE THREAD

**Issue by fshot** [replicatedhq/ship#1014]
### Expected behavior
When including inline assets, the generated files should use the file mode specified within the ship.yaml

### Actual behavior

File modes are created seemingly randomly:

snippet from ship.yaml:
```
assets:
  v1:
    - inline:
        dest: 755.txt
        mode: 755
        contents: testing
    - inline:
        dest: 766.txt
        mode: 766
        contents: testing
    - inline:
        dest: 700.txt
        mode: 700
        contents: testing          
    - inline:
        dest: 644.txt
        mode: 644
        contents: testing
```
produces the following:

```
--w----r--    1 frank  staff     7 Jul  3 14:21 644.txt # mode ends up 204, not 644
--w-r-xr--    1 frank  staff     7 Jul  3 14:21 700.txt  # mode ends up 254, not 700
--wxr----x    1 frank  staff     7 Jul  3 14:21 755.txt # mode ends up 641, not 755
--wxr-xr--    1 frank  staff     7 Jul  3 14:21 766.txt # mode ends up 654, not 766
```
### Information

- Ship version: 0.47.3
- Docker version: 18.09.2
- Command line run: ```ship init replicated.app/ship-test-1-1```

### Steps to reproduce the behavior

1. Create a ship.yaml with inline assets, specifying mode
2. Run through ship init with the above, and audit the file permissions for the generated inline assets
