### ISSUE TITLE
Kustomized k8s yaml turns `"yes"` string into `yes` boolean

### ISSUE THREAD

**Issue by emosbaugh** [replicatedhq/ship#1035]
### Expected behavior
yes should remain a string in the rendered yaml

### Actual behavior
`"yes"` changes from string type to bool type in kustomize dest rendered yaml

### Information

- Ship version: 0.49.0
- Docker version: 18.09.5
- Command line run: `ship init replicated.app...`

### Steps to reproduce the behavior

1. create `ship.yaml`
```yaml
assets:
  v1:
  - inline:
      contents: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: redis
          labels:
            component: redis
        spec:
          replicas: 1
          selector:
            matchLabels:
              component: redis
          template:
            metadata:
              labels:
                component: redis
            spec:
              containers:
                - name: redis
                  image: redis
                  args: ["--appendonly", "yes"]
      dest: base/redis-deployment.yaml
      mode: 0644
config:
  v1: []
lifecycle:
  v1:
    - config:
        invalidates: ["render"]
    - render:
        requires: ["config"]
        root: "."
    - kustomize:
        requires: ["render"]
        base: ./base
        overlay: overlays/ship
        dest: rendered.yaml
```
2. `ship init --headless ship.yaml`
3. cat rendered.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      component: redis
  template:
    metadata:
      labels:
        component: redis
    spec:
      containers:
      - args:
        - --appendonly
        - yes
        image: redis
        name: redis
```
4. `kubectl apply -f rendered.yaml`
```
Error from server: error when applying patch:
...
for: "rendered.yaml": unrecognized type: string
```
