### ISSUE TITLE
Adding resources and running ship update with a kustomize step fails to add new resources to the kustomization.yaml

### ISSUE THREAD

**Issue by emosbaugh** [replicatedhq/ship#1036]
### Expected behavior
Newly added resources will get added to the kustomization.yaml file when added to the ship app after running ship update.

### Actual behavior
Newly added resources do not get added to the kustomization.yaml file when added to the ship app after running ship update.

### Information

- Ship version: 0.49.0
- Docker version: 18.09.5
- Command line run: `ship init replicated.app...`

### Steps to reproduce the behavior

1. create `ship.yaml`
```yaml
assets:
  v1:
  - inline:
      contents: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: redis
          labels:
            component: redis
        spec:
          replicas: 1
          selector:
            matchLabels:
              component: redis
          template:
            metadata:
              labels:
                component: redis
            spec:
              containers:
                - name: redis
                  image: redis
      dest: base/redis-deployment.yaml
      mode: 0644
config:
  v1: []
lifecycle:
  v1:
    - config:
        invalidates: ["render"]
    - render:
        requires: ["config"]
        root: "."
    - kustomize:
        requires: ["render"]
        base: ./base
        overlay: overlays/ship
        dest: rendered.yaml
```
2. `ship init --headless ship.yaml`
3.  edit `ship.yaml` add a second k8s yaml file
```yaml
assets:
  v1:
  - inline:
      contents: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: redis
          labels:
            component: redis
        spec:
          replicas: 1
          selector:
            matchLabels:
              component: redis
          template:
            metadata:
              labels:
                component: redis
            spec:
              containers:
                - name: redis
                  image: redis
      dest: base/redis-deployment.yaml
      mode: 0644
  - inline:
      contents: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: redis2
          labels:
            component: redis2
        spec:
          replicas: 1
          selector:
            matchLabels:
              component: redis2
          template:
            metadata:
              labels:
                component: redis2
            spec:
              containers:
                - name: redis2
                  image: redis
      dest: base/redis2-deployment.yaml
      mode: 0644
config:
  v1: []
lifecycle:
  v1:
    - config:
        invalidates: ["render"]
    - render:
        requires: ["config"]
        root: "."
    - kustomize:
        requires: ["render"]
        base: ./base
        overlay: overlays/ship
        dest: rendered.yaml
```
4. `ship update --headless ship.yaml`
5. 
```bash
$ tree
.
├── base
│   ├── kustomization.yaml
│   ├── redis2-deployment.yaml
│   └── redis-deployment.yaml
├── overlays
│   ├── defaults
│   │   ├── chart-patch.json
│   │   ├── heritage-patch.json
│   │   └── kustomization.yaml
│   └── ship
│       └── kustomization.yaml
├── rendered.yaml
└── ship.yml

$ cat base/kustomization.yaml 
kind: ""
apiversion: ""
resources:
- redis-deployment.yaml
```
