### ISSUE TITLE
Add support for patchesJson6902

### ISSUE THREAD

**Issue by tblaisot** [replicatedhq/ship#1037]
### Expected behavior

Adding `patchesJson6902` field in the main `kustomisation.yaml` file should work as in kustomize when using ship update

### Actual behavior

Ship update delete all added field in `kustomization.yaml` 

### Information

- Ship version: 0.49.0
- helm: 2.14.1
- kustomize: 2.0.3
- terraform: 0.11.14
- Docker version: 18.09.7
- Command line run: ship update

### Steps to reproduce the behavior

1. do a `ship init git::https://gitlab.com/charts/gitlab/`
2. create any patch
3. create a file `my-patch.json` containing: 
```
[{"op":"remove","path":"/metadata/labels/release"}]
```
3. edit the root `kustomization.yaml` to add
```
patchesJson6902:
  - target:
      kind: Deployment
      namespace: default
      name: gitlab-unicorn
    path: my-patch.json
```
4. do a `ship update`
5. open  root `kustomization.yaml` => the added code has disappeared 

Even if the UI doesn't support such avanced kustomization it will be nice if it doesn't delete all or if there was a way to add patches because kustomize patchesStrategicMerge doesn't allow deletion of resources
