### ISSUE TITLE
Docker asset with dest GCR repository with json_key authentication returns unauthorized

### ISSUE THREAD

**Issue by emosbaugh** [replicatedhq/ship#1054]
### Expected behavior

Dest target should work with gcr json key credentials.

### Actual behavior

Request returns unauthorized

```
ts=2019-08-27T16:04:12.784496253Z caller=github.com/replicatedhq/ship/pkg/lifecycle/render/docker/step.go level=debug step.type=render render.phase=execute asset.type=docker dest="docker://{{repl ConfigOption \"registry_auth\"}}{{repl ConfigOption \"registry_address\"}}/alpine:latest" description= event=execute.fail.withRegistrySecret err="unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication"
```

### Information

- Ship version: 0.50.0

### Steps to reproduce the behavior

username: _json_key
password: `cat key.json  | jq -c . | pbcopy`

Example yaml

```yaml
---
assets:
  v1:
    - docker:
        image: alpine:latest
        source: public
        dest: docker://{{repl ConfigOption "registry_auth"}}{{repl ConfigOption "registry_address"}}/alpine:latest

config:
  v1:
  - name: registry
    title: Docker Registry
    description: Configure the Docker Registry path and authentication information. This Docker Registry will store the Bugsnag images that are required for Clustered Edition.
    items:
    - name: registry_address
      title: Docker Registry path
      help_text: The path of the Docker Registry. The Registry should be addressable with the same path from both this machine and the Kubernetes cluster.
      type: text
      required: true
    - name: registry_username
      title: Username
      type: text
      default: ""
      affix: left
    - name: registry_password
      title: Password
      type: text
      default: ""
      affix: right
    - name: registry_auth
      readonly: true
      value: '{{repl ConfigOption "registry_username" | UrlEncode}}:{{repl ConfigOption "registry_password" | UrlEncode}}@'

lifecycle:
  v1:
    - config:
        invalidates: ["render"]
    - render:
        requires: ["config"]
        root: .
```
