### ISSUE TITLE
Add Render attribute "Root" to Lifecycle 

### ISSUE THREAD

**Issue by ebramanti** [replicatedhq/ship#294]
`Asset` currently has a shared attribute (in `AssetShared`) called `Dest`, which specifies where the file should be output. However, Ship still maintains control over what the root of the asset output is internally.

For example, the `app` command has a root for assets of `./installer`, whereas `init` has a root of the current working directory.

To make this configurable, we want to add a new attribute to the `Render` step, `Root`, which makes this root directory configurable. The `Root` attribute will be relative to the current working directory.

Here is an example of what this would look like in a `release.yml`:
```yaml
---
assets:
  v1:
    - inline:
        contents: |
          #!/bin/bash
          echo "installing nothing"
        dest: scripts/install.sh
        mode: 511
    - inline:
        contents: |
          #!/bin/bash
          echo "tested nothing"
        dest: scripts/test.sh
        mode: 511
lifecycle:
  v1:
    - render:
        root: assets
```

The `root` key will be an optional attribute on render, and will default to the `app` command's previous internal default: `installer`.
