### ISSUE TITLE
Cannot create an overlay patch to an empty spec

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/ship#364]
### Expected behavior
Clicking on a base YAML that is an empty spec should generate a patch where I can add new items.

### Actual behavior
Clicking on the base YAML does nothing.

### Information

- Ship version: 72306f5
- Command line run:  ship init github.com/helm/charts/grafana

### Steps to reproduce the behavior

1. `ship init github.com/helm/charts/grafana`
2. Change the `ingress` key of the values.yaml to:
```yaml
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels: {}
  hosts: {}
  path: /grafana
```
3. On the kustomize step, select the ingress.yaml and click on "rules" to add a rule. Nothing happens.

This should create a new patch to overwrite the rules key.
