### ISSUE TITLE
Helm Template should create the destination directory

### ISSUE THREAD

**Issue by laverya** [replicatedhq/ship#373]
### Expected behavior
```
---
assets:
  v1:
  - helm:
      dest: charts/rendered
      helm_ref:
        chart_ref: stable/mysql
        version: "0.8.3"
config: {}
lifecycle:
  v1:
  - render: {}
```
should work and render a helm chart within `charts/rendered`.

### Actual behavior
Ship fails with the error `execute plan: 1 error occurred:\n\n* execute templating: failed to move rendered chart dir: rename .ship/tmp-rendered/mysql installer/charts/rendered: no such file or directory`

If the directory already exists, such as if an inline file is created there, ship runs successfully.
```
  - inline:
      contents: |
        this exists to create the charts directory
        it should be removed when that bug is resolved
      dest: ./charts/mkdir.sh
      mode: 0777
```

### Information

- Ship version: master as of https://github.com/replicatedhq/ship/commit/72306f59103f640d561a3a1d5b5730d6d0b42b4f
- Docker version: ...
- Command line run: ./bin/ship app --log-level=debug --runbook=./fixtures/app.yml

### Steps to reproduce the behavior

1. Place the above spec into ./fixtures/app.yml
2. Compile and run with `make run` or `./bin/ship app --log-level=debug --runbook=./fixtures/app.yml`
3. Observe failure
