### ISSUE TITLE
The github asset cannot pull paths ending with `/`

### ISSUE THREAD

**Issue by laverya** [replicatedhq/ship#449]
### Expected behavior

```
assets:
  v1:
    - github:
        repo: replicatedhq/test-charts
        path: template-functions/
        dest: ./github-slash
        source: public
        ref: ad1e78d13c33fae7a7ce22ed19920945ceea23e9
    - github:
        repo: replicatedhq/test-charts
        path: template-functions
        dest: ./github-noslash
        source: public
        ref: ad1e78d13c33fae7a7ce22ed19920945ceea23e9
```
should produce files within the github-slash and github-noslash directories.

### Actual behavior
No files are created in the github-slash directory.

### Information

- Ship version: master as of https://github.com/replicatedhq/ship/commit/1a62988845c9648e3f3f521d365d6ecfd71640e3

### Steps to reproduce the behavior

1. Add the above example to a ship yaml
2. Run it
