### ISSUE TITLE
The github asset type should allow trimming the path

### ISSUE THREAD

**Issue by laverya** [replicatedhq/ship#476]
### Expected behavior
That there be a way to place the contents of a folder in a git repo (`docs/component/`) directly within a folder on the filesystem (`mydocs/`)

### Actual behavior
Given an asset:
```
assets:
  v1:
    - github:
        repo: anexample/repo
        path: "docs/component"
        dest: ./mydocs
        source: public
        ref: master
```
Files always contain the full path from the git repo and will be placed within `mydocs/docs/component` on the filesystem.
