### ISSUE TITLE
The amazon_eks resource should template its parameters

### ISSUE THREAD

**Issue by laverya** [replicatedhq/ship#478]
### Expected behavior
```
assets:
  v1:
    - amazon_eks:
        dest: new/new_vpc.tf
        cluster_name: {{repl ConfigOption "cluster_name" }}
        region: "us-west-2"
...
```
should produce a cluster with the name provided by the template function

### Actual behavior
it produces a cluster with the name `{{repl ConfigOption "cluster_name" }}`

### Information

- Ship version: master as of https://github.com/replicatedhq/ship/commit/6f3dd933085e219e51cbc50c71c8e008bd892a7e
- Docker version: irrelevant

### Steps to reproduce the behavior

1. attempt to use a template function within an amazon_eks resource
2. observe failure
