### ISSUE TITLE
Continue button missing from us message step after browser is closed

### ISSUE THREAD

**Issue by emosbaugh** [replicatedhq/ship#549]
### Expected behavior
continue button should show up on intro screen. title does in some cases. not sure what the expected behavior is here

### Actual behavior
continue button doesn't show up on intro screen when you revisit it. title does

### Information
First run:
<img width="1407" alt="screen shot 2018-09-06 at 11 37 18 am" src="https://user-images.githubusercontent.com/371319/45178120-bf403880-b1c9-11e8-8f6f-5052c4f73ca6.png">
Subsequent run:
<img width="1383" alt="screen shot 2018-09-06 at 11 37 22 am" src="https://user-images.githubusercontent.com/371319/45178121-bf403880-b1c9-11e8-9a50-228a4712e50b.png">

```json
{
    "version": "0.14.0",
    "git": "d12fe4c",
    "buildTime": "2018-08-29T17:49:28Z"
}
```

### Steps to reproduce the behavior

```yaml
lifecycle:
  v1:
  - message:
      contents: |
        This tool will prepare assets to deploy BLAH to your Kubernetes cluster.
```

1. Run ship
1. Open browser link
1. Click continue
1. Close browser window
1. Open browser link
