### ISSUE TITLE
Github assets with proxy:false don't have template functions run

### ISSUE THREAD

**Issue by laverya** [replicatedhq/ship#716]
### Expected behavior
Template functions should be run on all github assets.
### Actual behavior
Template functions are run on proxied github assets, but not ones downloaded directly.
### Information

- Ship version: 0.25.0
- Docker version: ...
- Command line run:

### Steps to reproduce the behavior

1. run ship with an asset like this:
```
  - github:
      repo: replicatedhq/test-charts
      path: template-functions/
      dest: ./github-template-funcs
      ref: ad1e78d13c33fae7a7ce22ed19920945ceea23e9
```
2. look at the output and see that template funcs have not been run.
