### ISSUE TITLE
Built-in support for SealedSecrets?

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/ship#802]
This is a feature request/proposal to include [SealedSecrets](https://github.com/bitnami-labs/sealed-secrets) support natively in Ship.

Ship is built for and recommends a GitOps workflow. Secret management can be difficult in this process. There are several ways that folks can manage secrets when using GitOps:

1) Manage secrets out of band. This might include using a specific tool such as Hashicorp Vault or a cloud providers KMS. Alternatively, out-of-band secret management could simply be manually deploying secrets using `kubectl` to prevent them from being commited.

2) Check the secrets in to source control. This is not advisable, even in a private repo because secrets often contain sensitive data and should not be shared in a git repo.

3) Encrypting the secrets and committing only the encrypted secret to the GitOps repo. This is possible with an operator such as Bitnami's SealedSecret controller. 

Ship, when using a `ship.yaml` file, could have native, built-in support for managing these better. Today, a cluster operator is expected to bring both an opinion and knowledge about how to mange secrets. Instead, Ship could recommend one of the solutions above and have built-in, native support for the workflow.

To kickstart this conversation, I'm proposing that Ship have native support for the SealedSecrets controller. We could have support for this in a way that does not require the `kubeseal` binary to be installed, but instead it could be vendored in or implemented in Ship directly.

This would be useful to prompt for a SealedSecret cert, and use it to create SealedSecret objects. For example, in a ship.yaml, an asset could look like:

```yaml
assets:
  v1:
    - inline:
        dest: ./sealedsecret.yaml
        contents: |
          ---
          apiVersion: bitnami.com/v1alpha1
          kind: SealedSecret
          metadata:
            name: my-secret
            namespace: '{{repl ConfigOption "namespace"}}'
          spec:
            encryptedData:
              password: '{{repl KubeSeal (ConfigOption "sealed_secret_cert") (ConfigOption "namespace") (ConfigOption "password") }}'
              privateKey: '{{repl KubeSeal (ConfigOption "sealed_secret_cert") (ConfigOption "namespace") (ConfigOption "private_key") }}'
```

The Kubeseal template function would be invoked on the render step, and have this definition:

```go
func (ctx ConfigCtx) kubeSeal(cert string, namespace string, clearText string) string {
        ...
}
```

**Comment by dexhorthy** [comment]
This makes sense to me. An alternative might be to have an asset type that implements this behavior

```
assets:
  v1:
    - sealedSecret:
        dest: ./sealedsecret.yaml
        cert: '{{repl ConfigOption "sealed_secret_cert"}}'
        namespace: '{{repl ConfigOption "namespace"}}'
        data:
           password: '{{repl ConfigOption "password"}}'
           privateKey: '{{repl ConfigOption "private_key"}}'
```

But I think the template function approach is a bit more flexible.
