### ISSUE TITLE
Proposal: Include resources and patches in ship.yaml

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/ship#806]
This is proposal for a new feature.

I'd like to be able to include resources in my ship.yaml that will be added as resources or patches to the generated kustomization.

To illustrate, let's start with a basic ship.yaml snippet that shows the need for this feature:

```yaml
assets:
  v1:
    - inline:
        dest: ./overlays/ship/sealedsecret.yaml
        when: '{{repl ConfigOptionEquals "sealed_secrets" "sealed_secrets"}}'
        contents: |
          ---
          apiVersion: v1
          apiVersion: bitnami.com/v1alpha1
          kind: SealedSecret
          metadata:
            name: signalsciences
            namespace: default
          spec:
            encryptedData:
              accessKeyId: '{{repl KubeSeal ... }}"

lifecycle:
  v1:
    # ... removed for clarity

    - kustomize:
        requires: ["render"]
        base: installer/base
        overlay: overlays/ship
        dest: output.yaml  
```

In this example, if the cluster operator chooses to write out the sealed secret in the ship init workflow, it will successfully be created in the overlays/ship directory. But the new resource will not be added to the kustomization.yaml, and it won't be visible on the /kustomize step. Finally, it won't be included in the generated output.yaml because it's not in the kustomization.yaml.

I'd like to find a way to deliver predefined or optional patches and resources to be included in the generated ship overlay.

Proposals:

**1) Automatically add all assets to kustomization.yaml**  
One approach would be for the kustomize render step to list the files that are already present in the "overlay" directory, and determine how to handle them. This step would have to include determining if the file is a kubernetes resource, and then determining if it's a patch or a new resource by comparing the GVK with everything in the base directory. Then, it could include this file in the kustomization.yaml and it would be included in the output.

**2) Allow the application packager to list these files**
Another approach is to change the schema of the kustomize lifecycle step to allow the runbook author to specify included resources and patches. These would have to be included only if present on the filesystem, to respect the optionality of the assets. This schema could look like:

```
- kustomize:
    requires: ["render"]
    base: installer/base
    overlay: overlays/ship
    dest: output.yaml
    resources:
      - overlays/ship/sealedsecret.yaml
    patches: []
```

---

There are likely other options to solve this also, and additional options for consideration should be added to this issue.

I propose that option 1 (automatically add) is a cleaner solution. Is there a use case where an application packager would expect to write a kubernetes resource to overlays/ship (in the above example) and _not_ expect it to be added automatically?

**Comment by laverya** [comment]
I agree that automatically adding is a lot cleaner! My only worry there would be differentiating between overlays and resources, but it should be possible to differentiate by comparing GVK+names with existing files.

**Comment by dexhorthy** [comment]
I would vote for some variant of option 2 (also have an alternative in Option 3 below). I think auto-detecting resources in the "base" is super valuable, but we should open the door to extra patches and resources defined by the packager.

I think letting the packager control the finer grained detail of the kustomization makes a lot of sense, patches, resources, JSON6902 patches, etc. Rather than just limiting them to defining a base.

For option one, there was a proposal to just continue auto-detecting everything, but I think that determining whether a manifest is a patch or a resource is a non-trivial exercise, without requiring some kind of additional annotation hijinks or something.

I'd also like to propose:

### Option 3) Allow advanced users to a kustomization YAML as an "inline" asset

```yaml
assets:
  v1:
    - inline:
        dest: ./base/kustomization.yaml
        contents: |
          resources: []
          patches: []
          namespace: {{repl ConfigOption "namespace"}}
          ... etc
```

When running a `lifecycle.v1.kustomize`, and a kustomization.yaml exists in the specified `base`, we can either:

- just use that YAML instead of auto-detecting
- assume everything else in `base` is a resource, and merge those into the `resources` array of the existing kustomization yaml. (packager-supplied patches would have to live outside the `base` directory, which I think is fine if not recommended)

The first option is a little more clear whats going on, and easier to adopt. The second is a non-breaking change, is easier to migrate from the current setup, and is more opt-in.
