### ISSUE TITLE
Github assets should respect the render root

### ISSUE THREAD

**Issue by laverya** [replicatedhq/ship#814]
### Expected behavior
With a root of `.` specified, Github assets should be placed in folders relative to that render root

```
lifecycle:
  v1:
    - render:
        root: .
```

### Actual behavior
Github assets are always placed relative to `installer/`.

### Information

- Ship version: master as of b99f3ae5a3c2900d0d53dbb31ac5382f7dec6d0c

### Steps to reproduce the behavior

1. Run ship with the `ship.yaml` included below
2. Observe that Github assets are created relative to `installer/`, not `.`

```
assets:
  v1:
    - github:
        dest: ../base/common
        repo: kubernetes/ingress-nginx
        path: deploy/mandatory.yaml
        ref: nginx-0.22.0
        proxy: false
        strip_path: true

    - github:
        dest: ../base
        repo: kubernetes/ingress-nginx
        path: deploy/provider/aws/service-l4.yaml
        ref: nginx-0.22.0
        proxy: false
        strip_path: true

    - github:
        dest: base
        repo: kubernetes/ingress-nginx
        path: deploy/provider/aws/
        ref: nginx-0.22.0
        proxy: false
        strip_path: true

    - github:
        dest: ../overlays/cloud
        repo: kubernetes/ingress-nginx
        path: deploy/provider/aws/patch-configmap-l4.yaml
        ref: nginx-0.22.0
        proxy: false
        strip_path: true
config:
  v1: []

lifecycle:
  v1:
    - render:
        root: .
    - message:
        contents: "outro"
```
