### ISSUE TITLE
Helm Values-From should support file paths, not just directories

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/ship#877]
### Expected behavior

If I want to do something like in https://github.com/replicatedhq/ship/issues/872#issuecomment-475172383, hard coding a path to a helm values file, ship should support both:

1. A path to a directory containing a `values.yaml` file
2. A path to a YAML file contains the values.

Today we only support 1, but 2 makes more sense (to me at least).

```
            - helm:
                dest: ./installer/base
                helm_fetch:
                  chart_ref: external-dns
                  repo_url: https://kubernetes-charts.storage.googleapis.com
                  version: "1.7.0"
                values_from:
                  path: ./external-dns-values.yaml
```

### Actual behavior

To make this work today, only a directory is supported:

```
.
└── my-values
    └── values.yaml
```
```
                values_from:
                  path: ./my-values # must be a directory
```

### Information

- Ship version: 0.35.1
