### ISSUE TITLE
Config Options of type "label" are written to state.json

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/ship#906]
### Expected behavior

With this config item:

```yaml
      - name: https_label
        when: '{{repl ConfigOptionEquals "enable_ssl" "1" }}'
        title: Requests will be encrypted. HTTP requests will be redirected to HTTPS.
        type: label
```
 is used, it should not have any effect on `state.json`, as its merely around presentation logic.

### Actual behavior

The following is added to `state.json#config.v1` 

```
      "https_label": "",
```

### Information

- Ship version: 0.39.0
