### ISSUE TITLE
Bug: in base file \n after helm render

### ISSUE THREAD

**Issue by zendril** [replicatedhq/ship#917]
### Expected behavior
I am using `inline` to add a helm template into the ./templates dir of a helm chart.
This is a ConfigMap that contains xml inside.
This works and the file ends up in the templates dir successfully and looks fine.

After `render` I expect that the file that ends up in `base` looks like a normal xml inside of the data section.

### Actual behavior
After `render` it ends up with `\n` for all of the line endings of the xml inside the data section of the ConfigMap.

### Information

- Ship version: 0.40.0 Windows
- Docker version: N/A
- Command line run: `ship init ship.yaml`

### Steps to reproduce the behavior

1. Create ship.yaml with something like this:
```
assets:
  v1:
    - github:
          repo: jfrog/charts
          path: stable/artifactory-ha
          strip_path: true
          dest: chart
          ref: master
    - inline:
        dest: chart/templates/artifactory-binarystore.yaml
        contents: |+
          kind: ConfigMap
          apiVersion: v1
          metadata:
            name: {{ template "artifactory-ha.fullname" . }}-bs
            labels:
              app: {{ template "artifactory-ha.name" . }}
              chart: {{ template "artifactory-ha.chart" . }}
              heritage: {{ .Release.Service }}
              release: {{ .Release.Name }}
          data:
            binarystore.xml: |-
              <config version="4">
                  <chain>
                       lots of XMLy goodness in here
                  </chain>
               </config>
config:
  v1: []
lifecycle:
  v1:
    - message:
        contents: |
          Prepping for Artifactory-HA...
    - render:
        root: .
    - helmIntro: {}
    - helmValues:
        path: chart/values.yaml
    - render:
        root: .
        assets:
          v1:
            - helm:
                dest: base/artifactory-ha
                helm_opts:
                  - --name=test-artifactory
                local:
                  chart_root: ./chart
                values_from:
                  # hack, helmValues still needs a configurable dest path for us to store the output
                  path: .ship/tmp
    - kustomizeIntro: {}
    - kustomize:
        base: base
        overlay: overlays/ship
        dest: artifactory-ha-all.yaml
    - message:
        contents: |
          ## All set
          You can deploy Artifactory to your cluster with:
              kubectl apply -f artifactory-ha-all.yaml
```
2. `ship init ship.yaml`
