### ISSUE TITLE
License info is not preserved in `ship edit`

### ISSUE THREAD

**Issue by laverya** [replicatedhq/ship#960]
### Expected behavior
The output of `{{repl ShipCustomerRelease }}` is the same when running in `ship edit`

### Actual behavior
Output license info is zeroed out, like this:
```
license:
  id: ""
  assignee: ""
  createdAt: 0001-01-01T00:00:00Z
  expiresAt: 0001-01-01T00:00:00Z
  type: ""
```

### Information

- Ship version: 0.44.0
- Command line run: 
  - `ship init --headless staging.replicated.app/laverya-ship-1?license_id=UdFjHwMV9iF-Mbni4LYtTahh2K-l8QgW`
  - `mv installer installer.bak`
  - `ship edit`
  - `diff installer installer.bak`

### Steps to reproduce the behavior

1. Run a ship app that uses the `ShipCustomerRelease` template function
2. Backup the rendered files
3. Run `ship edit`
4. Compare the outputs

The ship yaml used:
```
assets:
  v1:
    - inline:
        dest: ./configOption.txt
        contents: |
          length = "{{repl ConfigOption "id_length" }}"

    - inline:
        dest: ./customerRelease.txt
        contents: |
          {{repl ShipCustomerRelease }}
config:
  v1:
    - name: id
      items:
         - name: id_length
           title: ID Length
           type: text
           required: true
           default: 80
           help_text: bigger numbers make longer ids

lifecycle:
  v1:
    - message:
        contents: "hi"
    - render: {}
    - message:
        contents: "bye"
```
