### ISSUE TITLE
Failed to init Keycloak with postgres subchart dependency

### ISSUE THREAD

**Issue by dave08** [replicatedhq/ship#965]
### Expected behavior
Finishes the ship init process

### Actual behavior
Gets stuck when saving the values with a `[ERROR] templates/: render error in "keycloak/templates/statefulset.yaml": template: keycloak/templates/_helpers.tpl:50:12: executing "keycloak.postgresql.fullname" at <{{template "postgresql.fullname" $postgresContext}}>: template "postgresql.fullname" not defined` error

### Information

- Ship version: 0.40.0
- Docker version: 17.05.0-ce
- Command line run: `ship init https://github.com/codecentric/helm-charts/tree/master/charts//keycloak`

### Steps to reproduce the behavior

values.yaml:
```yaml
keycloak:
  persistence:
    deployPostgres: true
    dbVendor: postgres
```
